[package]
name = "proto_pdk"
version = "0.4.4"
edition = "2021"
license = "MIT"
description = "A plugin development kit for creating proto WASM plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_pdk_api = { version = "0.4.5", path = "../pdk-api" }
anyhow = "1.0.72"
extism-pdk = { workspace = true }
once_cell = { workspace = true }
once_map = { workspace = true }
serde = { workspace = true }
