[package]
name = "proto_node"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Node.js support for proto."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.1.4", path = "../core" }
clean-path = "0.2.1"
log = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
assert_fs = "1.0.10"
tokio = { workspace = true }
