[package]
name = "proto_pdk_test_utils"
version = "0.25.0"
edition = "2021"
license = "MIT"
description = "Utilities for testing proto WASM plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.37.3", path = "../core" }
proto_pdk_api = { version = "0.21.1", path = "../pdk-api" }
warpgate = { version = "0.15.0", path = "../warpgate" }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }
toml = { version = "0.8.14", optional = true }

[features]
default = []
schema = ["dep:toml"]
