[package]
name = "proto_pdk_test_utils"
version = "0.35.6"
edition = "2024"
license = "MIT"
description = "Utilities for testing proto WASM plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.47.11", path = "../core" }
proto_pdk_api = { version = "0.27.6", path = "../pdk-api" }
warpgate = { version = "0.23.8", path = "../warpgate" }
extism = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }

[features]
default = []
schema = []
