[package]
name = "proto_pdk_test_utils"
version = "0.21.0"
edition = "2021"
license = "MIT"
description = "Utilities for testing proto WASM plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.34.2", path = "../core" }
proto_pdk_api = { version = "0.17.4", path = "../pdk-api" }
warpgate = { version = "0.11.8", path = "../warpgate" }
extism = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_sandbox = { workspace = true }
toml = { version = "0.8.12", optional = true }

[features]
default = []
schema = ["dep:toml"]
