[package]
name = "proto_pdk_test_utils"
version = "0.3.8"
edition = "2021"
license = "MIT"
description = "Utilities for testing proto WASM plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.14.6", path = "../core" }
proto_pdk_api = { version = "0.4.6", path = "../pdk-api" }
proto_wasm_plugin = { version = "0.4.5", path = "../wasm-plugin" }
extism = { workspace = true }
