[package]
name = "warpgate_api"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "APIs for working with warpgate plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
